version: '3'

services:
  master:
    image: actionml/spark:latest
    command: master
    ports:
      - 8080:8080

  worker:
    image: actionml/spark:latest
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8081:8081
      - 7077:7077
    environment:
      - SPARK_WORKER_MEMORY=16g
      - SPARK_WORKER_CORES=8 
      - SPARK_DAEMON_MEMORY=8g
      - SPARK_MASTER_IP=147.100.18.116
